server.port=${LOCAL_DK_SERVER_PORT}

# Datasource H2
spring.datasource.url=jdbc:h2:mem:${LOCAL_DK_DB_NAME}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${LOCAL_DK_DB_USERNAME}
spring.datasource.password=${LOCAL_DK_DB_PASSWORD}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Show on the web console of H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

management.endpoints.web.exposure.include=health